### ISSUE TITLE
Mysterious "-n" file dropped into build directory

### ISSUE THREAD

**Issue by rbayliss** [docksal/backstopjs#1]
Hey, thanks a lot for putting this together!  It works beautifully, except that when I run it, I always end up with a file named "-n" dropped into the volume I have mounted at /src.  It appears to be X-Server related (it contains MIT-MAGIC-COOKIE-1).  Any idea what this is about or how to fix it?

**Comment by lmakarov** [comment]
Thanks for reporting. I noticed this as well a while back. It's a minor and non-obvious thing. Maybe someone eventually will have an explanation for this :)

**Comment by Decipher** [comment]
I have also noticed this issue. Not super helpful, but I will try to look further into it if I move forward using this service.

**Comment by lmakarov** [comment]
I think this might be fixed with the latest upgrade to BackstopJS v3.
Please repot here if you notice it still happening.
