### ISSUE TITLE
Please upgrade to backstop latest + chrome 

### ISSUE THREAD

**Issue by garris** [docksal/backstopjs#4]

**Comment by lmakarov** [comment]
Adding some context to this request: https://github.com/garris/BackstopJS/issues/547

**Comment by lmakarov** [comment]
@garris would you be interested in an official `backstopjs/backstopjs` Docker image for BackstopJS?

**Comment by garris** [comment]
Yes!!!

**Comment by garris** [comment]
Please let me know how I can help with this.

**Comment by lmakarov** [comment]
Sure, ping me in Gitter: https://gitter.im/lmakarov

**Comment by fusionfox** [comment]
I've noticed that https://hub.docker.com/r/backstopjs/backstopjs/ now exists, should we stop using this docker image and use that instead?

**Comment by garris** [comment]
Yes!  Please do -- and please send feedback if you run into any issues.  @lmakarov was kind enough to set this up for us and it's my intention to maintain it.   I am hoping to announce the new feature in a week or so -- but would be great to have a few people start validating that the build is working.   Please let me know if it's working for you.

Cheers.
