### ISSUE TITLE
Rebuild on DockerHub

### ISSUE THREAD

**Issue by ataylorme** [docksal/backstopjs#5]
@lmakarov first of all thanks so much for creating this image! It's been super helpful.

Any chance you can rebuild this on Docker Hub? The [latest build](https://hub.docker.com/r/docksal/backstopjs/builds/bpa2crv5v8urmj9noj9zfke/) is 3 months old and has Chrome 61. I'd like to test Chrome 63 as in addition to Backstop JS I'm running Lighthouse performance tests. Chrome 63 has a fix for network throttling in headless mode. See [this issue](https://github.com/GoogleChrome/lighthouse/issues/2675#issuecomment-350799018) for details.

**Comment by lmakarov** [comment]
@ataylorme Glad you found this image helpful :)
A few month ago I "donated" it to the [BackstopJS](https://github.com/garris/BackstopJS) project, so you should post this request in their issue queue.

Everyone is encouraged to use the official `backstopjs/backstopjs` image at this point. I'll add a note in README about this.

Assuming alpine edge has Chromium 63, it would be a single line change here:
https://github.com/garris/BackstopJS/blob/master/docker/Dockerfile#L56

**Comment by ataylorme** [comment]
Thanks for donating, I didn't realize there was a Backstop official one. I will chat over there.
