### ISSUE TITLE
Mark repository as archived

### ISSUE THREAD

**Issue by BBlackwo** [docksal/backstopjs#6]
Hey could this repo be marked as archived so people know to go to the offical one? 

https://help.github.com/articles/archiving-repositories/

This one is still at the top of Google when searching for "backstopjs docker".

**Comment by lmakarov** [comment]
@BBlackwo archiving the repo won't stop it from being indexed by search engines, but yeah, it probably makes sense to have it archived anyway. I also added `[DEPRECATED]` in the repo description and README title.
